fediverse:
    instance_url: https://social.23.nu
    username: md+fediarchive@foxel.org
    password: iPaiketig0yaisho
    token: ZDK4MDBHOTKTMMVKNY0ZYTVLLWEZYTKTNDI5MGFJYTBLODUW
    token_exp: ""
s3:
    endpoint: s3.dornseif.cloud
    access_key: GK9bcded255d5caee54fe65f78
    secret_key: fa22e0f886d0186c5cff209485109429e3c039042bd513a248b905b2c8b494fd
    bucket: archivebox-in
    use_ssl: true
settings:
    max_posts_per_user: 5000
    include_visibility:
        - public
        - unlisted
        - private
    blacklisted_domains:
        - example.com
        - test.blacklist.com
        - natur.23.nu
    rss_feeds:
        - https://natur.23.nu/feeds/c/kulturlandschaft.xml
        - https://natur.23.nu/c/solarpunk
        - https://natur.23.nu/c/streuobst
        - https://natur.23.nu/c/forst
        - https://natur.23.nu/c/bergisch
        - https://natur.23.nu/c/bezugsquellen
        - https://natur.23.nu/c/gartenbau
        - https://natur.23.nu/c/bau 
        - https://natur.23.nu/c/erleben
        - https://natur.23.nu/c/news



